rootProject.name = "library-provider-backend"

include(":model")
project(":model").projectDir = file("src/domain/model")

include(":usecase")
project(":usecase").projectDir = file("src/domain/usecase")

include(":app-main")
project(":app-main").projectDir = file("src/application/app-main")

include(":mongo-repository")
project(":mongo-repository").projectDir = file("src/infrastructure/driven-adapters/mongo-repository")

include(":reactive-web")
project(":reactive-web").projectDir = file("src/infrastructure/entry-points/reactive-web")

include(":serializer")
project(":serializer").projectDir = file("src/infrastructure/helpers/serializer")
